### PR TITLE
cta update

### PR DESCRIPTION
**Pull request by kcbreuil**

### CODE REVIEW

**Review by asasmith — CHANGES_REQUESTED** [review]
Can you split this into 2 separate pr's? One for the the link fix one for removing the `<Quote>` component.

**Comment by kcbreuil** [comment]
@asasmith this was just meant to be homepage updates

**Comment by asasmith** [comment]
I still think we need to be in better habit of separating work into more appropriate (and hopefully smaller) pr's, especially when it's qa items that are being worked on. `Homepage updates` doesn't give us a lot of context for what this work is or why it was done.

**Comment by kcbreuil** [comment]
> I still think we need to be in better habit of separating work into more appropriate (and hopefully smaller) pr's, especially when it's qa items that are being worked on. `Homepage updates` doesn't give us a lot of context for what this work is or why it was done.

sounds good! @asasmith I have submitted it!

**Review by asasmith — APPROVED** [review]

**Pull request merged**
